<?php
/**
 * Created by PhpStorm.
 * User: Johan
 * Date: 2016-01-17
 * Time: 20:16
 */

namespace HelmutSchneider\Swish\Tests;


use HelmutSchneider\Swish\Client;
use HelmutSchneider\Swish\Util;

class ClientTest extends Test
{

    /**
     * @var Client
     */
    public $client;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $guzzle = new \GuzzleHttp\Client();
        $baseUrl = 'https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1';
        $options = [
            'verify' => __DIR__ . '/../_data/ca.crt',
            'cert' => __DIR__ . '/../_data/cl.crt',
            'ssl_key' => [__DIR__ . '/../_data/key.pem', 'swish'],
        ];
        $this->client = new Client($guzzle, $baseUrl, $options);
    }

    public function testCreateGetPaymentRequest()
    {
        $res = $this->client->createPaymentRequest([
            'callbackUrl' => 'https://localhost/swish',
            'payeePaymentReference' => '12345',
            'payerAlias' => '4671234768',
            'payeeAlias' => '1231181189',
            'amount' => '100',
            'currency' => 'SEK',
        ]);

        codecept_debug($res->getStatusCode());
        codecept_debug($res->getHeaders());

        $this->assertEquals(201, $res->getStatusCode());
    }

}
