<?php
/**
 * Created by PhpStorm.
 * User: Johan
 * Date: 2016-01-17
 * Time: 20:16
 */

namespace HelmutSchneider\Swish\Tests;


use HelmutSchneider\Swish\Client;
use HelmutSchneider\Swish\Util;

class ClientTest extends Test
{

    /**
     * @var Client
     */
    public $client;

    /**
     * @var array
     */
    private $paymentRequest = [
        'callbackUrl' => 'https://localhost/swish',
        'payeePaymentReference' => '12345',
        'payerAlias' => '4671234768',
        'payeeAlias' => '1231181189',
        'amount' => '100',
        'currency' => 'SEK',
    ];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $rootCert = __DIR__ . '/../_data/ca.crt';
        $clientCert = __DIR__ . '/../_data/cl.crt';
        $privateKey = [__DIR__ . '/../_data/key.pem', 'swish'];
        $this->client = Client::make($rootCert, $clientCert, $privateKey, Client::SWISH_TEST_URL);
    }

    public function testCreateGetPaymentRequest()
    {
        $res = $this->client->createPaymentRequest($this->paymentRequest);

        codecept_debug($res->getStatusCode());
        codecept_debug($res->getHeaders());

        $this->assertEquals(201, $res->getStatusCode());

        $id = Util::getPaymentRequestIdFromResponse($res);
        $res = $this->client->getPaymentRequest($id);
        $body = Util::decodeResponse($res);

        codecept_debug($body);

        $this->assertEquals($id, $body['id']);
    }

}
